INSERT INTO  TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE)
VALUES (1001, 'Get AWS Certified', 'in28minutes', CURRENT_DATE(), false) ;

INSERT INTO  TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE)
VALUES (1002, 'Get Azure Certified', 'in28minutes', CURRENT_DATE(), false) ;

INSERT INTO  TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE)
VALUES (1003, 'Get GCP Certified', 'in28minutes', CURRENT_DATE(), false) ;

INSERT INTO  TODO (ID, DESCRIPTION, USERNAME, TARGET_DATE, DONE)
VALUES (1004, 'Get DevOps Certified', 'in28minutes', CURRENT_DATE(), false) ;
